CREATE TABLE _User (
    id bigint PRIMARY KEY AUTO_INCREMENT,
    userID VARCHAR(36) UNIQUE NOT NULL,
    username varchar(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    pass varchar(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);